version: "3"

services:

  redis:
    image: redis
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 10s
      timeout: 5s
      retries: 5
    user: gitlab-runner

  postgresql_db:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    user: gitlab-runner

  web_api:
    build: .
    tty: true
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/spa_habits
    ports:
      - '8000:8000'
    depends_on:
      postgresql_db:
        condition: service_healthy
      redis:
        condition: service_healthy
    user: gitlab-runner

  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO
    depends_on:
      - redis
      - web_api
    user: gitlab-runner

  celery_beat:
    build: .
    restart: always
    tty: true
    command: celery -A config beat -l INFO -S django
    depends_on:
      - redis
      - web_api
    user: gitlab-runner

volumes:
  pg_data:
