# Generated by Django 4.2.8 on 2023-12-17 15:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=300, null=True, verbose_name='Место')),
                ('started_at', models.TimeField(blank=True, null=True, verbose_name='Начало в')),
                ('action', models.TextField(max_length=1000, verbose_name='Действие')),
                ('periodicity', models.CharField(blank=True, choices=[('DAILY', 'Ежедневно'), ('EVERY_TWO_DAYS', 'Каждые два дня'), ('EVERY_THREE_DAYS', 'Каждые три дня'), ('EVERY_FOUR_DAYS', 'Каждые четыре дня'), ('EVERY_FIFTH_DAY', 'Каждый пятый день'), ('EVERY_SIXTH_DAY', 'Каждый шествой день'), ('WEEKLY', 'Еженедельно')], default='DAILY', max_length=25, null=True, verbose_name='Периодичность')),
                ('reward', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Вознаграждение')),
                ('action_time_in_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Длительность действия')),
                ('is_pleasant_habit', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('is_published', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('pleasant_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='habits.habit', verbose_name='Приятная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ('user',),
            },
        ),
        migrations.RemoveField(
            model_name='usefulhabit',
            name='pleasant_habit',
        ),
        migrations.RemoveField(
            model_name='usefulhabit',
            name='user',
        ),
        migrations.DeleteModel(
            name='PleasantHabit',
        ),
        migrations.DeleteModel(
            name='UsefulHabit',
        ),
    ]
