# Generated by Django 4.2.8 on 2023-12-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_rename_action_time_in_minutes_habit_action_time_in_second_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_message_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата/время последнего сообщения'),
        ),
    ]
