# Generated by Django 4.2.8 on 2023-12-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habit_last_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='last_message_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата-время последнего сообщения'),
        ),
    ]
